version: "3.8"
services:
  mysql:
    build: "./docker/mysql"
    container_name: jooq-example-mysql
    ports:
      - "23306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
